---
- name: Clone FTL git repo to grading host(s)
  git:
    repo: "{{ ftl_git_repo }}"
    dest: "{{ ftl_grading_host_home }}"
    version: "{{ ftl_git_branch | default('master') }}"
    force: yes
    # no_log: true
  tags:
    - clone-ftl-repo

- name: "Create custom fact directory for student metadata"
  file:
    path: "/etc/ansible/facts.d"
    state: "directory"

- name: "Insert opentlc custom facts e.g. student opentlc name"
  template:
     src: opentlc.fact.j2
     dest: /etc/ansible/facts.d/opentlc.fact
     mode: 0644

- name: Install grade script
  copy:
    src: grade_lab
    dest: /usr/local/bin/grade_lab
    mode: 0555

- name: Install grade debug script
  copy:
    src: grade_lab_debug
    dest: /usr/local/bin/grade_lab_debug
    mode: 0555

- name: Install solve script
  copy:
    src: solve_lab
    dest: /usr/local/bin/solve_lab
    mode: 0555
...
