---
  # Setup the FTL git repo on grader host
- include_tasks: insert-ftl-repo.yml

  # Create local facts from student and course metadata
- include_tasks: local-facts.yml

  # Setup the wrapper scripts called by students
- include_tasks: insert-wrapper-scripts.yml
...
