---
- name: Searching file for FAIL
  lineinfile:
    path: "{{ grader_working_dir }}/{{ grader_student_report_file }}"
    regex: "^FAIL.*"
    state: absent
  check_mode: true
  register: r_lab_pass

- when: r_lab_pass.changed | bool
  name: Report contains one or more FAILs
  set_fact:
    lab_passed:             false
    student_errors:         "{{ r_lab_pass.found }}"
    report_status_message:  FAILED

- when: not r_lab_pass.changed | bool
  name: Report contains no FAILs
  set_fact:
    lab_passed: true
    student_errors: "{{ r_lab_pass.found }}"
    report_status_message:  SUCCESS

- name: Output lab status and error count
  debug:
    msg: 
      - "lab_passed = {{ lab_passed }}"
      - "Error count = {{ student_errors }}"  
    verbosity: 2

- name: Finalize lab report with status
  lineinfile:
    dest:         "{{ grader_working_dir }}/{{ grader_student_report_file }}"
    insertafter:  EOF
    line: |

      {{ report_status_message }} {{ student_errors }} Errors

- name: Get report hash
  stat:
    path: "{{ grader_working_dir }}/{{ grader_student_report_file }}"
    checksum_algorithm: sha256
  register: r_st

- name: Sign student report
  lineinfile:
    path: "{{ grader_working_dir }}/{{ grader_student_report_file }}"
    line: "{{ r_st.stat.checksum }}  {{ grader_student_report_file }}"
...
